export const FETCHING_RECIPES = 'FETCHING_RECIPES';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_FAILURE = 'FETCH_RECIPES_FAILURE';
export const DELETE_RECIPE='DELETE_RECIPE'
export const ADD_RECIPE='ADD_RECIPE'