// RECIPES
export const FETCHING_RECIPES = 'FETCHING_RECIPES';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_FAILURE = 'FETCH_RECIPES_FAILURE';
export const DELETE_RECIPE='DELETE_RECIPE'
export const ADD_RECIPE='ADD_RECIPE'

// INGREDIENTS
export const FETCHING_INGREDIENTS = 'FETCHING_INGREDIENTS';
export const FETCH_INGREDIENTS_SUCCESS = 'FETCH_INGREDIENTS_SUCCESS';
export const FETCH_INGREDIENTS_FAILURE = 'FETCH_INGREDIENTS_FAILURE';
export const DELETE_INGREDIENT='DELETE_INGREDIENT'
export const ADD_INGREDIENT='ADD_INGREDIENT'
export const ADD_INGREDIENT_SUCCESS='ADD_INGREDIENT_SUCCESS'
export const ADD_INGREDIENT_FAILURE='ADD_INGREDIENT_FAILURE'
