// RECIPES
export const FETCHING_RECIPES = 'FETCHING_RECIPES';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_FAILURE = 'FETCH_RECIPES_FAILURE';
export const DELETE_RECIPE='DELETE_RECIPE'
export const ADD_RECIPE='ADD_RECIPE'

// INGREDIENTS
export const FETCHING_INGREDIENTS = 'FETCHING_INGREDIENTS';
export const FETCH_INGREDIENTS_SUCCESS = 'FETCH_INGREDIENTS_SUCCESS';
export const FETCH_INGREDIENTS_FAILURE = 'FETCH_INGREDIENTS_FAILURE';
export const REMOVING_USER_INGREDIENT='REMOVING_USER_INGREDIENT'
export const REMOVE_USER_INGREDIENT_SUCCESS='REMOVE_USER_INGREDIENT_SUCCESS'
export const REMOVE_USER_INGREDIENT_FAILURE='REMOVE_USER_INGREDIENT_FAILURE'
export const ADDING_INGREDIENT='ADDING_INGREDIENT'
export const ADD_INGREDIENT_SUCCESS='ADD_INGREDIENT_SUCCESS'
export const ADD_INGREDIENT_FAILURE='ADD_INGREDIENT_FAILURE'

// AUTH
export const USER_LOADING='USER_LOADING'
export const USER_LOADED='USER_LOADED'
export const AUTH_ERROR='AUTH_ERROR'
export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_FAIL='LOGIN_FAIL'
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS'
export const LOGOUT_FAIL='LOGOUT_FAIL'
export const REGISTER_SUCCESS='REGISTER_SUCCESS'
export const REGISTER_FAIL='REGISTER_FAIL'
export const ADDING_USER_INGREDIENT='ADDING_USER_INGREDIENT'
export const ADD_USER_INGREDIENT_SUCCESS='ADD_USER_INGREDIENT_SUCCESS'
export const ADD_USER_INGREDIENT_FAILURE='ADD_USER_INGREDIENT_FAILURE'